### ISSUE TITLE
Mininum sidebar width

### ISSUE THREAD

**Issue by Kikobeats** [leo/material-ui#12]
I'm in love this theme. Congratulations!

I note that the minimum size of the sidebar is a little big:

<img width="468" alt="lol" src="https://cloud.githubusercontent.com/assets/2096101/15275360/c508cc26-1ac9-11e6-91eb-2c129adc7264.png">

When I change the UI theme for another (for example, default Atom UI) the interface allows me resize the sidebar and it is more small. In this UI this is the more little possible width is this (and is big for me 😄 ).

Is it means that it depends of a less variable? how I can edit it?

Also as you can see I change the background color:

```
@level-3-color: #2c3036
```

Do you think that could be possible apply this change without edit raw files?

**Comment by Kikobeats** [comment]
oh right I found it! Instead of min-width I added a margin-left:

``` less
 .tree-view-resizer {
-  min-width: 280px;
+  margin-right: 30px;
```

I don't know if you are interested in create a PR of this, but for me, now, looks AWESOME

**Comment by leo** [comment]
Hehe, thank you! Means a lot to me to see people like my stuff :blush: It seems like you've found a proper solution for this. However, I generally recommend that you shouldn't change the files contained within the theme, because they will all be overwritten after an update.

Instead of that, you should click this button in the menu bar and edit your user stylesheet:

![slice 1](https://cloud.githubusercontent.com/assets/6170607/15283720/f21a7cb8-1b4c-11e6-8c09-e701d3754e3a.png)

Currently, I think the size is okay for most users. But if another user thinks it's too big, I will definitely revisit this! :blush:

**Comment by Kikobeats** [comment]
@leo thanks for the reply!

yes, I know, but in the case of the background actually it is a less variable that affect different css classes. I setup it but doesn't work :'(

**Comment by leo** [comment]
@Kikobeats So what exactly doesn't work? The less variable for the background? If yes, then a PR would be highly appreciated.

**Comment by Kikobeats** [comment]
yes, but do you want have a PR with this color?

**Comment by leo** [comment]
Why not 😊

**Comment by Kikobeats** [comment]
that's the attitude! 💪

I think that this little change depend of the theme used for syntax.

I'm using [afterglow-monokay-syntax](https://atom.io/themes/afterglow-monokai-syntax) and as you can see in the preview, line counter background is colorized using the background color that I changed in your theme.

![screen shot 2016-05-16 at 11 22 29](https://cloud.githubusercontent.com/assets/2096101/15285612/806d4332-1b58-11e6-807a-6a899a06332b.png)
