### ISSUE TITLE
Tab italics conflict with "Use Preview Tabs" setting

### ISSUE THREAD

**Issue by IanVS** [leo/material-ui#2]
Hi, I am really liking this theme.  One problem I have though is that I use the preview tabs setting from the tabs core package.  This normally means that tabs open with an italicized title, until either a change is made or the file/tab is double-clicked (at which point it remains open as a non-preview tab and the text stops being italicized.  

It seems that in this theme, italicized text is always used when the editor is "dirty" with unsaved changes.  This means I cannot tell if a tab is in preview mode or not, which has caused some confusion.  Do you think you could stick with just using the pencil icon, and not change the style of the text?

**Comment by leo** [comment]
It took me a few minutes to understand what this option really does, but now I got it. The reason why I've italicized the titles was because Sublime Text's configuration has that "Preview Tabs" functionality enabled by default and I wanted to reproduce that for Atom, too.

But now I understand that this functionality already exists for Atom, it's just not enabled by default. So yes, I will definitely make the italicized title look normal again! :blush:

I'm happy that you like it, btw! :yum:

**Comment by IanVS** [comment]
Great, thanks!

**Comment by leo** [comment]
No problem! This change will be published with `v1.0.3`, by the way.

**Comment by IanVS** [comment]
Much better, thanks!

**Comment by leo** [comment]
@IanVS :blush:
